In [12]:
import pandas as pd
Boston = pd.read_csv('boston.csv')
Boston

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [13]:
x = Boston.iloc[:, 0:13]
y =  Boston['medv']
print(x.shape)
print(y.shape)

(506, 13)
(506,)

In [6]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [14]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [22]:
import statsmodels.api as sm
x_with_constant = sm.add_constant(x)
x_with_constant

,const,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,1.0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,1.0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,1.0,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,1.0,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,1.0,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,1.0,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,1.0,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,1.0,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,1.0,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,1.0,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [23]:
results = sm.OLS(y, x_with_constant).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     108.1
Date:                Wed, 21 Sep 2022   Prob (F-statistic):          6.72e-135
Time:                        04:52:14   Log-Likelihood:                -1498.8
No. Observations:                 506   AIC:                             3026.
Df Residuals:                     492   BIC:                             3085.
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.4595      5.103      7.144      0.000      26.432      46.487
crim          -0.1080      0.033     -3.287      0.001      -0.173      -0.043
zn             0.0464      0.014      3.382      0.001       0.019       0.073
indus          0.0206      0.061      0.334      0.738      -0.100       0.141
chas           2.6867      0.862      3.118      0.002       0.994       4.380
nox          -17.7666      3.820     -4.651      0.000     -25.272     -10.262
rm             3.8099      0.418      9.116      0.000       2.989       4.631
age            0.0007      0.013      0.052      0.958      -0.025       0.027
dis           -1.4756      0.199     -7.398      0.000      -1.867      -1.084
rad            0.3060      0.066      4.613      0.000       0.176       0.436
tax           -0.0123      0.004     -3.280      0.001      -0.020      -0.005
ptratio       -0.9527      0.131     -7.283      0.000      -1.210      -0.696
black          0.0093      0.003      3.467      0.001       0.004       0.015
lstat         -0.5248      0.051    -10.347      0.000      -0.624      -0.425
==============================================================================
Omnibus:                      178.041   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              783.126
Skew:                           1.521   Prob(JB):                    8.84e-171
Kurtosis:                       8.281   Cond. No.                     1.51e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.51e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [24]:
# drop insignificant variable
x_with_constant = x_with_constant.drop(['indus', 'age'], axis = 1)
results = sm.OLS(y, x_with_constant).fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   medv   R-squared:                       0.741
Model:                            OLS   Adj. R-squared:                  0.735
Method:                 Least Squares   F-statistic:                     128.2
Date:                Wed, 21 Sep 2022   Prob (F-statistic):          5.54e-137
Time:                        04:52:17   Log-Likelihood:                -1498.9
No. Observations:                 506   AIC:                             3022.
Df Residuals:                     494   BIC:                             3072.
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         36.3411      5.067      7.171      0.000      26.385      46.298
crim          -0.1084      0.033     -3.307      0.001      -0.173      -0.044
zn             0.0458      0.014      3.390      0.001       0.019       0.072
chas           2.7187      0.854      3.183      0.002       1.040       4.397
nox          -17.3760      3.535     -4.915      0.000     -24.322     -10.430
rm             3.8016      0.406      9.356      0.000       3.003       4.600
dis           -1.4927      0.186     -8.037      0.000      -1.858      -1.128
rad            0.2996      0.063      4.726      0.000       0.175       0.424
tax           -0.0118      0.003     -3.493      0.001      -0.018      -0.005
ptratio       -0.9465      0.129     -7.334      0.000      -1.200      -0.693
black          0.0093      0.003      3.475      0.001       0.004       0.015
lstat         -0.5226      0.047    -11.019      0.000      -0.616      -0.429
==============================================================================
Omnibus:                      178.430   Durbin-Watson:                   1.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              787.785
Skew:                           1.523   Prob(JB):                    8.60e-172
Kurtosis:                       8.300   Cond. No.                     1.47e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [27]:
# making pridictions
pred_medv = results.predict(x_with_constant)
pred_medv

0      30.124281
1      24.996528
2      30.533370
3      28.647995
4      27.982641
         ...
501    23.537900
502    22.380817
503    27.609999
504    26.111333
505    22.340843
Length: 506, dtype: float64

In [29]:
# cancatinating
Predicted_boston = pd.concat([x_with_constant, y,pd.DataFrame(pred_medv, columns=['Predicted_Price'])], axis = 1)
Predicted_boston

,const,crim,zn,chas,nox,rm,dis,rad,tax,ptratio,black,lstat,medv,Predicted_Price
0,1.0,0.00632,18.0,0,0.538,6.575,4.0900,1,296,15.3,396.90,4.98,24.0,30.124281
1,1.0,0.02731,0.0,0,0.469,6.421,4.9671,2,242,17.8,396.90,9.14,21.6,24.996528
2,1.0,0.02729,0.0,0,0.469,7.185,4.9671,2,242,17.8,392.83,4.03,34.7,30.533370
3,1.0,0.03237,0.0,0,0.458,6.998,6.0622,3,222,18.7,394.63,2.94,33.4,28.647995
4,1.0,0.06905,0.0,0,0.458,7.147,6.0622,3,222,18.7,396.90,5.33,36.2,27.982641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,1.0,0.06263,0.0,0,0.573,6.593,2.4786,1,273,21.0,391.99,9.67,22.4,23.537900
502,1.0,0.04527,0.0,0,0.573,6.120,2.2875,1,273,21.0,396.90,9.08,20.6,22.380817
503,1.0,0.06076,0.0,0,0.573,6.976,2.1675,1,273,21.0,396.90,5.64,23.9,27.609999
504,1.0,0.10959,0.0,0,0.573,6.794,2.3889,1,273,21.0,393.45,6.48,22.0,26.111333
505,1.0,0.04741,0.0,0,0.573,6.030,2.5050,1,273,21.0,396.90,7.88,11.9,22.340843

In [32]:
# Finding accuracy by each observation
Predicted_boston["Errors"] = abs(Predicted_boston['medv']-Predicted_boston['Predicted_Price'])/Predicted_boston['medv']
Predicted_boston

,const,crim,zn,chas,nox,rm,dis,rad,tax,ptratio,black,lstat,medv,Predicted_Price,Errors
0,1.0,0.00632,18.0,0,0.538,6.575,4.0900,1,296,15.3,396.90,4.98,24.0,30.124281,0.255178
1,1.0,0.02731,0.0,0,0.469,6.421,4.9671,2,242,17.8,396.90,9.14,21.6,24.996528,0.157247
2,1.0,0.02729,0.0,0,0.469,7.185,4.9671,2,242,17.8,392.83,4.03,34.7,30.533370,0.120076
3,1.0,0.03237,0.0,0,0.458,6.998,6.0622,3,222,18.7,394.63,2.94,33.4,28.647995,0.142276
4,1.0,0.06905,0.0,0,0.458,7.147,6.0622,3,222,18.7,396.90,5.33,36.2,27.982641,0.226999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,1.0,0.06263,0.0,0,0.573,6.593,2.4786,1,273,21.0,391.99,9.67,22.4,23.537900,0.050799
502,1.0,0.04527,0.0,0,0.573,6.120,2.2875,1,273,21.0,396.90,9.08,20.6,22.380817,0.086447
503,1.0,0.06076,0.0,0,0.573,6.976,2.1675,1,273,21.0,396.90,5.64,23.9,27.609999,0.155230
504,1.0,0.10959,0.0,0,0.573,6.794,2.3889,1,273,21.0,393.45,6.48,22.0,26.111333,0.186879
505,1.0,0.04741,0.0,0,0.573,6.030,2.5050,1,273,21.0,396.90,7.88,11.9,22.340843,0.877382

In [34]:
# Finding accuracy of overall model
1 - Predicted_boston.Errors.mean()

0.8357528910010064

In [35]:
# Making a predictions on unseen data - Make sure indus and age ie, variable not modeled are not available
new_house = pd.DataFrame({'const':[1], 'crim':[0.01], 'zn':[21.6], 'chas':[0], 'nox':[0.65], 'rm':[7.89],
                         'dis':[4.91], 'rad':[1.2], 'tax':[355.2], 'ptratio':[18.36], 'black':[476.28], 'lstat':[5.98]})
new_house

,const,crim,zn,chas,nox,rm,dis,rad,tax,ptratio,black,lstat
0,1,0.01,21.6,0,0.65,7.89,4.91,1.2,355.2,18.36,476.28,5.98

In [36]:
results.predict(new_house)

0    28.799117
dtype: float64